In [1]:
#numpy array

import numpy as np


In [2]:
#shape : show the dimension 

In [4]:
e = np.eye(3)

In [5]:
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
e.shape

(3, 3)

In [7]:
a = np.array([1,1,1,1,])

In [9]:
a.shape  # one dimension array, show the length

(4,)

In [14]:
c = np.array([[1,1],[1,2],[1,3],[1,4]])

In [15]:
c.shape, c.shape[0], c.shape[1]

((4, 2), 4, 2)

In [16]:
#zeros（）、ones（）、empty（）

In [18]:
a = np.zeros(4)

In [19]:
a

array([0., 0., 0., 0.])

In [20]:
b = np.ones([2,4])

In [21]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
c = np.ones([2,4], int)

In [23]:
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
d = np.empty([3,3,])

In [26]:
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a = np.arange(9)

In [28]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
b = a.reshape(3,3)

In [39]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
b[1]

array([3, 4, 5])

In [34]:
b[:,1]

array([1, 4, 7])

In [37]:
c = np.eye(3)

In [38]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
c[:,0]=b[:,1] #give the b's col2 to c's col1


In [41]:
c

array([[1., 0., 0.],
       [4., 1., 0.],
       [7., 0., 1.]])

In [42]:
#numpy 拼接数组1

In [44]:
a=np.array([1,2,5])

In [45]:
b=np.array([10,12,15])

In [46]:
a_list=list(a)

In [47]:
b_list=list(b)

In [48]:
a_list.extend(b_list)

In [50]:
a_list

[1, 2, 5, 10, 12, 15]

In [51]:
a=np.array(a_list)

In [52]:
a

array([ 1,  2,  5, 10, 12, 15])

In [53]:
#numpy 拼接数组2 numpy.append(arr, values, axis=None)

In [54]:
a=np.arange(5)

In [55]:
a

array([0, 1, 2, 3, 4])

In [56]:
np.append(a,10)

array([ 0,  1,  2,  3,  4, 10])

In [58]:
b=np.array([11,22,33])

In [59]:
np.append(a,b)

array([ 0,  1,  2,  3,  4, 11, 22, 33])

In [60]:
a=np.array([[1,2,3],[4,5,6]])

In [61]:
b=np.array([[11,21,31],[7,8,9]])

In [62]:
np.append(a,b) #变一维了

array([ 1,  2,  3,  4,  5,  6, 11, 21, 31,  7,  8,  9])

In [64]:
np.append(a,b).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 21, 31],
       [ 7,  8,  9]])

In [65]:
#numpy 拼接数组3 np.concatenate((a,b,c),axis=0) 

In [66]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
b

array([[11, 21, 31],
       [ 7,  8,  9]])

In [68]:
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 21, 31],
       [ 7,  8,  9]])

In [69]:
np.concatenate((a,b),axis=1) #对应行拼对应行

array([[ 1,  2,  3, 11, 21, 31],
       [ 4,  5,  6,  7,  8,  9]])

In [70]:
#nonzero()

In [71]:
a = [0,2,3]

In [72]:
b = np.nonzero(a)  

In [74]:
b  #返回数组a中非零元素的索引值数组。

(array([1, 2], dtype=int64),)

In [76]:
np.array(b).ndim  #dimenstion 为2 

2

In [77]:
a = np.array([[[0,1],[1,0]],[[0,1],[1,0]],[[0,0],[1,0]]])

In [79]:
b = np.nonzero(a)

In [83]:
b

(array([0, 0, 1, 1, 2], dtype=int64),
 array([0, 1, 0, 1, 1], dtype=int64),
 array([1, 0, 1, 0, 0], dtype=int64))

In [82]:
np.array(b).ndim

2

In [84]:
a

array([[[0, 1],
        [1, 0]],

       [[0, 1],
        [1, 0]],

       [[0, 0],
        [1, 0]]])

In [86]:
#a的数组结构如上所示，请将a想像为数量为3的一组小图片，每张图片的大小为2*2，下文中以num * row * col来分别表示其维度。
  #b包含3个长度为5的array，这意味着a有3维，且a共有5个非0值。
  #先说b中的第1个向量是[0, 0, 1, 1, 2]，这实际是a在num维度上描述的非零值。第0张图上有2个非零值，第1张图上有2个非零值，第2张图上有1个非零值。因此在num维度上的非零值数组为[0, 0, 1, 1, 2]。
  #b中的第2个向量是[0, 1, 0, 1, 1]，这实际是a在row维度上描述的非零值。由于row上的值只有0和1（只2行），所以只由0和1组成。
 

In [87]:
# random

In [88]:
# 产生3个[0, 1)之间的数组成的向量

In [89]:
a = np.random.random(3)

In [93]:
a

array([0.66242076, 0.32821377, 0.0822182 ])

In [90]:
# 产生3个[0, 10)之间的数组成的向量

In [91]:
b = 10 * np.random.random(3)

In [94]:
b

array([7.7840208 , 6.22902669, 4.76921561])

In [97]:
c = np.random.random([3,2])

In [98]:
c

array([[0.19706604, 0.18770877],
       [0.63445189, 0.6663518 ],
       [0.19189398, 0.12710531]])

In [99]:
#numpy.linspace()

In [100]:
# 定义由6个[0, 2*pi)之间等距数据组成的向量

In [101]:
a = np.linspace(0, 2*np.pi, 6)

In [103]:
a

array([0.        , 1.25663706, 2.51327412, 3.76991118, 5.02654825,
       6.28318531])

In [104]:
a.reshape(2, 3)

array([[0.        , 1.25663706, 2.51327412],
       [3.76991118, 5.02654825, 6.28318531]])

In [105]:
#numpy.unique

In [106]:
A = [1, 2, 2, 5,3, 4, 3]

In [107]:
np.unique(A)

array([1, 2, 3, 4, 5])

In [108]:
C= ['fgfh','asd','fgfh','asdfds','wrh']

In [110]:
np.unique(C)

array(['asd', 'asdfds', 'fgfh', 'wrh'], dtype='<U6')

In [111]:
a, s,p = np.unique(A, return_index=True, return_inverse=True) # s是新表元素在旧表的位置， p是旧在新

In [112]:
a

array([1, 2, 3, 4, 5])

In [113]:
s

array([0, 1, 4, 5, 3], dtype=int64)

In [114]:
p

array([0, 1, 1, 4, 2, 3, 2], dtype=int64)

In [115]:
#bool的个数

In [116]:
boolarr = np.array([[0, 0, 1], [1, 0, 1], [1, 0, 1]], dtype=np.bool)

In [117]:
boolarr

array([[False, False,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [118]:
np.sum(boolarr)

5

In [119]:
np.count_nonzero(boolarr)

5

In [120]:
# np.where(condition, x, y)

In [125]:
import random

In [127]:
x = np.random.randn(2,3)

In [128]:
x

array([[-0.02957165, -1.05025842,  0.86513726],
       [ 1.01107865, -0.23700834, -0.74507127]])

In [129]:
np.where(x>0, 1, -1)


array([[-1, -1,  1],
       [ 1, -1, -1]])